apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: atipaday-subscription
spec:
  topic: tips-created
  routes:
    default: /tips
  pubsubname: tipspubsub
scopes:
- atipaday-telegram
- atipaday